name: PHP tests
on: [push, pull_request]
jobs:
  # Check there is no syntax errors in the project
  php-linter:
    name: PHP Syntax check 5.6
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: PHP syntax checker 5.6
        uses: prestashop/github-action-php-lint/5.6@master

  # Check the PHP code follow the coding standards
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Run PHP-CS-Fixer
        uses: prestashopcorp/github-action-php-cs-fixer@master
